# -*- coding: utf-8 -*-
"""insurance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zofkl7_IlEIcAy_tK6bAV0PQqZoVqrmz
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

df = pd.read_csv('/content/insurance-data.csv')
df

df.info()

df.describe().round()

df.duplicated().sum()

df[df.duplicated()]

df.drop_duplicates(inplace = True)

df.duplicated().sum()

df.isna().sum().all()

def apply(age):
  if age <= 2 :
    return 'Babys'
  elif age <= 12 :
    return 'Children'
  elif age <= 17 :
    return 'Teenagers'
  elif age <= 39 :
    return 'Young_Adults'
  elif age <= 59 :
    return 'Middle_Adults'
  else :
    return 'Old_Adults'

Age_categories = df['age'].apply(apply)
Age_categories.value_counts()

df.insert(1,'Age_categories',Age_categories)
df.head(2)

sns.lineplot(data = df , x = 'Age_categories' , y = 'charges')
plt.show()

"""## **Insight**

- the older you get , the higher insurence price (linear)
"""

sex_charges = df.groupby('sex').agg({'charges' : 'mean'})
sex_charges

plt.pie(sex_charges['charges'],labels=sex_charges.index , autopct='%1.1f%%')
plt.show()

"""## **Insight**

- Males is pay more than female

"""

def apply(x):
  if x <= 20 :
    return '10-20'
  elif x <= 30 :
    return '21-30'
  elif x <= 40 :
    return '31-40'
  elif x <= 50 :
    return '41-50'
  else :
    return '51-60'

bmi_categories = df['bmi'].apply(apply)
bmi_categories.value_counts()

df.insert(4,'bmi_categories',bmi_categories)

df.head(2)

bmi_charges = df.groupby('bmi_categories').agg({'charges' : 'mean'})
bmi_charges

plt.bar(bmi_charges.index , bmi_charges['charges'])
plt.show()

"""## **Insight**

- the higher bmi , the higher pay charges
"""

df['children'].value_counts()

children_charges = df.groupby('children').agg({'charges' : 'mean'})
children_charges

plt.bar(children_charges.index , children_charges['charges'])
plt.show()

smoker_charges = df.groupby('smoker').agg({'charges':'mean'})
smoker_charges

plt.pie(smoker_charges['charges'],labels = ['No' ,'Yes'] ,autopct = '%1.1f%%')
plt.show()

"""## **Insight**

- Smokers is pay much more than other
"""

df['region'].value_counts()
region_charges = df.groupby('region').agg({'charges':'mean'})
region_charges

plt.bar(region_charges.index,region_charges['charges'])
plt.show()

"""## Final Concloution  :

- there is a row duplicated
- there is no missing values
- the older you get , the higher insurence price (linear)
- Males is pay more than female
- the higher bmi , the higher pay charges
- Smokers is pay much more than other
"""